/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Root_Query.graphql
 * @generated SignedSource<<1dd9f3c38ae932329ad45dbf0f3272a5>>
 * @relayHash af5d9cccd7c69e59cb948cde09bc169e
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query Root_Query {
  viewer {
    ...Book_viewer
  }
}

fragment Book_viewer on User {
  book {
    id
    title
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "Root_Query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Book_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "Root_Query",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "Root_Query",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Book",
            "name": "book",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "title",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query Root_Query {\n  viewer {\n    ...Book_viewer\n  }\n}\n\nfragment Book_viewer on User {\n  book {\n    id\n    title\n  }\n}\n"
};

module.exports = batch;
