
export const SESSION_KEY = 'SESSION_FRONTEND';
export const CALL_API = 'CALL_API';
export const RESOURCE_NOT_FOUND_CODE = 404;
export const UNAUTHORIZED_CODE = 401;
export const ACCESS_DENIED_CODE = 403;

export const ActionTypes = {
	CALL_API: 'CALL_API',
	RESET_STATE: 'RESET_STATE',
	DISPLAY_ERROR: 'DISPLAY_ERROR',
	FETCH_CONFIG_REQUEST: 'FETCH_CONFIG_REQUEST',
	FETCH_CONFIG_SUCCESS: 'FETCH_CONFIG_SUCCESS',
	FETCH_CONFIG_FAILURE: 'FETCH_CONFIG_FAILURE'
}